[package]
name = "my_crate"
version = "1.84.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]
name = "my_crate"

[dependencies]
uniffi = { version = "0.25.3", features = [ "cli" ] }

[build-dependencies]
uniffi = { version = "0.25.3", features = [ "build" ] }

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"
